language: cpp
dist: xenial

git:
  depth: 10

matrix:
# Linux/GCC
  include:
  - os: linux
    compiler: gcc           # g++-5, Qt5.12.0, IPC enabled
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        packages: [ g++-5 qt512base qt512declarative ]
    env: COMPILER=g++-5 QT=512 DISABLE_IPC=OFF
  - os: linux
    compiler: gcc           # g++-5, Qt5.12.0, IPC disabled
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        packages: [ g++-5 qt512base qt512declarative ]
    env: COMPILER=g++-5 QT=512 DISABLE_IPC=ON
# Linux/Clang
  - os: linux
    compiler: clang          # clang-6.0, Qt5.12.0, IPC enabled
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        packages: [ clang-6.0 libstdc++-6-dev qt512base qt512declarative ]
    env: COMPILER=clang++-6.0 QT=512 DISABLE_IPC=OFF
# OSX/Clang
  - os: osx
    osx_image: xcode9.2
    compiler: clang
    env: COMPILER=clang++ DISABLE_IPC=OFF

  # TODO: all combined-inprocess-async-... tests fail, if IPC is disabled. The interface never becomes ready.
  allow_failures:
  - env: COMPILER=g++-5 QT=512 DISABLE_IPC=ON

install: ./travis/install.sh

before_script: ./travis/before_script.sh

script:
- cd build
- >
  cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_PREFIX_PATH=${Qt5_DIR} -DCMAKE_BUILD_TYPE=Release -DFACELIFT_DISABLE_DBUS_IPC=${DISABLE_IPC}
  -DFACELIFT_BUILD_TESTS=ON ..
- make -j2 && dbus-launch make check
